#!/usr/bin/ansible-playbook
---
- name: 九、部署监控
  hosts: all
  gather_facts: true
  serial: 10
  become: yes
  any_errors_fatal: true
  become_method: sudo
  vars:
      monitor_result: "监控部署完成"
      monitor_bin_dir: /usr/local/yay/bin
  tasks:
    - name: 上传监控视图创建和用户授权脚本
      copy: src=./monitorview.sql dest=/home/postgres force=yes backup=no owner=postgres group=postgres mode=0775
      when: inventory_hostname == groups["master"][0]

    - name: 执行监控视图创建和用户授权脚本
      become: yes
      become_method: sudo
      become_user: postgres
      shell: psql -d putong-{{ servername }} -f /home/postgres/monitorview.sql
      when: inventory_hostname == groups["master"][0]

    - name: 安装 Debian 监控依赖
      apt:
        update_cache: yes
        name:
          - prometheus-postgres-exporter
        state: present
      when: ansible_os_family == "Debian"

    - name: 创建监控二进制目录
      file: path={{ monitor_bin_dir }} state=directory

    - block:
         - shell: cd {{ monitor_bin_dir }} && rm -rf postgres_exporter shannon_exporter pgbouncer_exporter queries.yaml
         - shell: cd {{ monitor_bin_dir }} && wget 10.9.12.126:9999/exportbin/postgres_exporter -O postgres_exporter
         - shell: cd {{ monitor_bin_dir }} && wget 10.9.12.126:9999/exportbin/shannon_exporter -O shannon_exporter
         - shell: cd {{ monitor_bin_dir }} && wget 10.9.12.126:9999/exportbin/pgbouncer_exporter -O pgbouncer_exporter
         - shell: cd {{ monitor_bin_dir }} && wget 10.9.12.126:9999/queries.yaml -O queries.yaml
         - shell: cd {{ monitor_bin_dir }} && chmod +x postgres_exporter shannon_exporter pgbouncer_exporter
         - file: path=/etc/sv/{{ item }} state=directory
           with_items:
                 - prometheus-pgbouncer-exporter
                 - prometheus-postgres-exporter
                 - prometheus-shannon-exporter
         - copy: src=../templates/monitor_template/pgbouncer_exporter_run.j2 dest=/etc/sv/prometheus-pgbouncer-exporter/run force=yes backup=yes owner=root group=root mode=0775
         - copy: src=../templates/monitor_template/shannon_exporter_run.j2 dest=/etc/sv/prometheus-shannon-exporter/run force=yes backup=yes owner=root group=root mode=0775
         - template: src=../templates/monitor_template/postgres_exporter_run.j2 dest=/etc/sv/prometheus-postgres-exporter/run force=yes backup=yes owner=root group=root mode=0775
         - file: src=/etc/sv/{{ item }} dest=/etc/service/{{ item }} state=link
           with_items:
                 - prometheus-pgbouncer-exporter
                 - prometheus-postgres-exporter
                 - prometheus-shannon-exporter
         - shell: sv stop prometheus-pgbouncer-exporter && sv start prometheus-pgbouncer-exporter
         - shell: sv stop prometheus-postgres-exporter && sv start prometheus-postgres-exporter
         - shell: sv stop prometheus-shannon-exporter && sv start prometheus-shannon-exporter
      when:
         - ansible_service_mgr != "systemd"
         - ansible_distribution_major_version == "6"

    - block:
         - shell: cd {{ monitor_bin_dir }} && rm -rf shannon_exporter pgbouncer_exporter queries.yaml
         - shell: cd {{ monitor_bin_dir }} && wget 10.9.12.126:9999/exportbin/shannon_exporter -O shannon_exporter
         - shell: cd {{ monitor_bin_dir }} && wget 10.9.12.126:9999/exportbin/pgbouncer_exporter -O pgbouncer_exporter
         - shell: cd {{ monitor_bin_dir }} && wget 10.9.12.126:9999/queries.yaml -O queries.yaml
         - shell: cd {{ monitor_bin_dir }} && chmod +x shannon_exporter pgbouncer_exporter
         - template: src=../templates/monitor_template/prometheus-pgbouncer-exporter.service.j2 dest=/etc/systemd/system/prometheus-pgbouncer-exporter.service force=yes backup=yes owner=root group=root mode=0644
         - template: src=../templates/monitor_template/prometheus-postgres-exporter.service.j2 dest=/etc/systemd/system/prometheus-postgres-exporter.service force=yes backup=yes owner=root group=root mode=0644
         - template: src=../templates/monitor_template/prometheus-shannon-exporter.service.j2 dest=/etc/systemd/system/prometheus-shannon-exporter.service force=yes backup=yes owner=root group=root mode=0644
         - systemd:
             daemon_reload: yes
             name: "{{ item }}"
             enabled: yes
             state: restarted
           loop:
             - prometheus-pgbouncer-exporter
             - prometheus-postgres-exporter
             - prometheus-shannon-exporter
      when: ansible_service_mgr == "systemd"

    - name: 获取主机名
      shell: hostname
      register: hostname

    - name: 获取主机名前缀
      shell: hostname | awk -F'.' {'print $1'}
      register: host_num

    - name: 获取机器角色
      shell: hostname | awk -F'.' {'print $2'}
      register: host_role

    - name: 变量注册
      set_fact:
          config_role: "{{ servername }}-{{ host_role.stdout }}"
          config_id: "{{ servername }}{{ host_num.stdout }}{{host_role.stdout}}{{ host_num.stdout }}"

    - name: 创建 consul 配置目录
      file: path=/etc/consul/conf.d state=directory

    - name: 写入 consul 主配置
      shell: echo '{"domain":"p1staff.com","data_dir":"/var/lib/consul/","rejoin_after_leave":true,"client_addr":"127.0.0.1","server":false,"retry_join":["10.191.224.32","10.191.224.33","10.191.224.34"],"node_name":"{{ hostname.stdout }}","datacenter":"bjs","bind_addr":"{{ inventory_hostname }}"}'>/etc/consul/consul.json

    - name: 清理 consul 服务注册配置
      shell: cd /etc/consul/conf.d && rm -rf *

    - name: 写入 node exporter consul 注册
      shell: echo '{"service":{"name":"prometheus-node-exporter-{{ config_role }}","id":"{{ config_id }}.node_exporter","tags":[],"port":9100}}' > /etc/consul/conf.d/prometheus-node-exporter-{{ config_role }}.json

    - name: 写入 pgbouncer exporter consul 注册
      shell: echo '{"service":{"name":"prometheus-pgbouncer-exporter-{{ config_role }}","id":"{{ config_id }}.pgbouncer_exporter","tags":[],"port":9127}}' > /etc/consul/conf.d/prometheus-pgbouncer-exporter-{{ config_role }}.json

    - name: 写入 postgres exporter consul 注册
      shell: echo '{"service":{"name":"prometheus-postgres-exporter-{{ config_role }}","id":"{{ config_id }}.postgres_exporter","tags":[],"port":9185}}' > /etc/consul/conf.d/prometheus-postgres-exporter-{{ config_role }}.json

    - name: 写入 shannon exporter consul 注册
      shell: echo '{"service":{"name":"prometheus-shannon-exporter-{{ config_role }}","id":"{{ config_id }}.shannon_exporter","tags":[],"port":9101}}' > /etc/consul/conf.d/prometheus-shannon-exporter-{{ config_role }}.json

    - name: 收集服务信息
      service_facts:

    - name: 重启 consul 服务
      systemd:
        name: consul
        state: restarted
      when:
        - ansible_service_mgr == "systemd"
        - "'consul.service' in ansible_facts.services"

    - name: 重新加载 consul 配置
      shell: /usr/local/yay/bin/consul reload
      when: ansible_service_mgr == "systemd"
      ignore_errors: yes

    - name: 监控部署结果
      debug: msg="RESULT-{{ monitor_result }}"
