#!/usr/bin/ansible-playbook
---
- name: 七、开始环境的后置检查工作
  hosts: all
  gather_facts: false
  serial: 20
  become: yes
  any_errors_fatal: true
  become_method: sudo
  vars:
    RESULT: "Database cluster initialization completed"
  tasks:
    - name: postgres 实例存活 CHECK
      become: yes
      become_method: sudo
      become_user: postgres
      shell: /usr/pgsql/bin/pg_ctl -D /mnt/storage00/pg/data status

    - name: postgres readiness CHECK
      shell: /usr/pgsql/bin/pg_isready -h 127.0.0.1 -p 5432

    - name: pgbouncer 实例存活 CHECK
      shell: ps -ef | grep 'pgbouncer.ini' | grep -v grep && exit 0 || exit 1

    - name: 注册业务库名与业务用户名（均 = servername）
      set_fact:
        username: "{{ servername }}"
        dbname: "{{ servername }}"
      when: inventory_hostname == groups["master"][0]

    - name: 获取业务用户的密码
      shell: "awk '{ for (i=1;i<=NF;i++) if ($i ~ /^password:/) { sub(/^password:/, \"\", $i); print $i; exit } }' /home/postgres/.userinfo.conf"
      register: business_user_passswd
      no_log: true
      when: inventory_hostname == groups["master"][0]

    - name: 注册业务用户密码
      set_fact:
        password: "{{ business_user_passswd.stdout }}"
      no_log: true
      when: inventory_hostname == groups["master"][0]

    - name: 主库验证用户连通性
      shell: psql -U {{ username }} -p 6432 -h 127.0.0.1 -d {{ servername }} -AXtqc "select 'master instance install success ,check OK'"
      environment:
        PGPASSWORD: "{{ password }}"
      register: check_connresult
      when: inventory_hostname == groups["master"][0]
      no_log: true

    - name: 主库验证用户连通性结果
      debug: msg="主库连通性CHECK PASS"
      when: inventory_hostname == groups["master"][0]

    - name: 业务用户write权限TEST
      shell: psql -U {{ username }} -p 6432 -h 127.0.0.1 -d {{ servername }} -AXtqc "insert into yay.init_result_check_table(check_result) values('ok')"
      environment:
        PGPASSWORD: "{{ password }}"
      when: inventory_hostname == groups["master"][0]
      no_log: true

    - name: 业务用户read权限TEST
      shell: psql -U {{ username }} -p 6432 -h 127.0.0.1 -d {{ servername }} -AXtqc "select check_result from yay.init_result_check_table order by id desc limit 1"
      environment:
        PGPASSWORD: "{{ password }}"
      when: inventory_hostname == groups["master"][0]
      register: check_queryresult
      no_log: true

    - name: 业务用户read权限测试结果
      debug: msg="业务用户read权限测试结果PASS {{ check_queryresult.stdout }}"
      when: inventory_hostname == groups["master"][0]

    - name: 检查主库侧复制情况
      become: yes
      become_method: sudo
      become_user: postgres
      shell: psql -AXtqc 'select count(*) from pg_stat_replication'
      register: primary_replication_result
      when: inventory_hostname == groups["master"][0] and (groups['slave'] | length > 0 or groups['offline'] | length > 0)

    - name: 检查备库侧复制情况
      become: yes
      become_method: sudo
      become_user: postgres
      shell: psql -AXtqc 'select count(*) as repstat from pg_stat_wal_receiver'
      register: standby_replication_result
      when: inventory_hostname != groups["master"][0]

    - name: 主从复制CHECK结果
      debug: msg="集群主从复制状况情况OK"
      when: inventory_hostname != groups["master"][0] and standby_replication_result.stdout|int == 1

    - name: 主库复制CHECK结果
      debug: msg="主库复制连接检查OK {{ primary_replication_result.stdout }}"
      when: inventory_hostname == groups["master"][0] and (groups['slave'] | length > 0 or groups['offline'] | length > 0) and primary_replication_result.stdout|int >= 1

    - name: 数据库集群初始化完成
      debug: msg="{{ RESULT }}"
